spring:
  application:
    name: config-server

server:
  port: 8888

---

spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: file:///${user.dir}/config

---

spring:
  profiles: docker
  cloud:
      config:
        server:
          git:
            uri: https://github.com/weinfurtner-io/config.git
